name: Build and Security Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    name: Build, SonarQube Scan + Security Report
    runs-on: windows-latest
    
    steps:
      # Étape 1: Checkout du code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2: Analyse SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://devsecops.ngrok.app

      # Étape 3: Générer un rapport OWASP Dependency-Check
      - name: Run OWASP Dependency-Check
        run: |
          # Télécharge et exécute Dependency-Check
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-8.3.0-release.zip
          unzip dependency-check-8.3.0-release.zip -d dependency-check
          ./dependency-check/bin/dependency-check.bat --project "${{ github.repository }}" --scan . --format HTML --format JSON --out ./security-reports/

      # Étape 4: Publier le rapport HTML comme artefact
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: ./security-reports/dependency-check-report.html

      # Étape 5 (Optionnelle): Bloquer le workflow si vulnérabilités critiques
      - name: Check for Critical CVEs
        run: |
          $criticalFound = Select-String -Path "./security-reports/dependency-check-report.json" -Pattern '"severity": "CRITICAL"'
          if ($criticalFound) {
            Write-Output "Des vulnérabilités critiques ont été détectées. Voir le rapport."
            exit 1
          }
