name: Build and Security Analysis

on:
  push:
    branches: [main]

jobs:
  build-and-analyze:
    name: Build, SonarQube Scan + Security Report
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://devsecops.ngrok.app

      - name: Run OWASP Dependency-Check
        shell: pwsh
        run: |
          # Utilisez le chemin absolu et vérifiez que Java est installé
          java -version
          
          # Exécutez Dependency-Check depuis votre installation locale
          $DCHECK_PATH = "${{ github.workspace }}\dependency-check\bin\dependency-check.bat"
          & $DCHECK_PATH --project "${{ github.repository }}" --scan . `
            --format HTML --format JSON `
            --out ./security-reports/ `
            --disableYarnAudit --disableNodeAudit  # Désactive les analyseurs optionnels si nécessaire

          # Vérifiez que le rapport a été généré
          if (-not (Test-Path "./security-reports/dependency-check-report.json")) {
              Write-Error "Le rapport Dependency-Check n'a pas été généré"
              exit 1
          }

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: |
            ./security-reports/dependency-check-report.html
            ./security-reports/dependency-check-report.json

      - name: Check for Critical CVEs
        shell: pwsh
        run: |
          $reportPath = "./security-reports/dependency-check-report.json"
          $criticalCount = (Get-Content $reportPath | ConvertFrom-Json).dependencies.where{
              $_.vulnerabilities.severity -contains "CRITICAL"
          }.Count
          
          if ($criticalCount -gt 0) {
              Write-Output "::error::$criticalCount vulnérabilités CRITIQUES détectées"
              exit 1
          }
          Write-Output "Aucune vulnérabilité critique trouvée"
